version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"  # avoid local MySQL conflicts
    volumes:
      - mysql_data:/var/lib/mysql  # persist MySQL data

  web:
    build: .
    container_name: messaging_web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

# Named volumes are defined here
volumes:
  mysql_data:
    driver: local
